---
apiVersion: k3d.io/v1alpha3
kind: Simple
name: k3s-test
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.21.7-k3s1
ports:
  - port: 7054:30054
    nodeFilters:
      - loadbalancer
  - port: 7050:30050
    nodeFilters:
      - loadbalancer
  - port: 7051:30051
    nodeFilters:
      - loadbalancer
  - port: 7052:30052
    nodeFilters:
      - loadbalancer