apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
  labels:
    app: orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer
  template:
    metadata:
      labels:
        app: orderer
    spec:
      containers:
        - name: orderer
          image: hashicorp/http-echo
          args:
            - "-text=orderer"
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 5678
---

kind: Service
apiVersion: v1
metadata:
  name: orderer-service
spec:
  selector:
    app: orderer
  type: LoadBalancer
  ports:
    - port: 5678 # Default port for image
      targetPort: 5678
      nodePort: 30050